#!/bin/bash

#                                      __
#    ____ _____  ____  ____ ___  ___  / /__
#   / __ `/ __ \/ __ \/ __ `__ \/ _ \/ //_/
#  / /_/ / / / / /_/ / / / / / /  __/ ,<
#  \__, /_/ /_/\____/_/ /_/ /_/\___/_/|_|
# /____/
#
# Adapted from https://gist.github.com/peterrus/e59a96688a4d49ee3d9302c0d3ff5fdd

set -e

DOTS_DIR="$HOME/.dots/gnome"

KEYS=()
KEYS+=("/org/gnome/desktop/wm/keybindings/")
KEYS+=("/org/gnome/desktop/wm/preferences/")
KEYS+=("/org/gnome/settings-daemon/plugins/media-keys/")
KEYS+=("/org/gnome/shell/keybindings/")

print_help() {
  printf "Usage: gnomek [backup|restore]\n"
}

if [[ $1 == "backup" ]]; then
  for key in "${KEYS[@]}"; do
    mkdir -p "$DOTS_DIR"/"$key"
    dconf dump "$key" > "$DOTS_DIR"/"$key".dconf
    printf "✅ %s\n" "$key"
  done

  exit 0
fi

if [[ $1 == 'restore' ]]; then
  for key in "${KEYS[@]}"; do
    dconf reset -f "$key"
    dconf load "$key" < "$DOTS_DIR"/"$key".dconf
    printf "✅ %s\n" "$key"
  done

  exit 0
fi

print_help
