#!/bin/bash

#     __          __         _     __
#    / /_  __  __/ /_  _____(_)___/ /________ _____  _____
#   / __ \/ / / / __ \/ ___/ / __  / ___/ __ `/ __ \/ ___/
#  / / / / /_/ / /_/ / /  / / /_/ / /__/ /_/ / /_/ (__  )
# /_/ /_/\__, /_.___/_/  /_/\__,_/\___/\__,_/ .___/____/
#       /____/                             /_/
#
#            MAPS CAPSLOCK TO CTRL & ESC

# FIXME: add option to toggle state
# FIXME: wayland support

setxkbmap -option ctrl:nocaps
killall xcape
xcape -e "Control_L=Escape"
