#!/bin/bash

#     __          __         _     __
#    / /_  __  __/ /_  _____(_)___/ /________ _____  _____
#   / __ \/ / / / __ \/ ___/ / __  / ___/ __ `/ __ \/ ___/
#  / / / / /_/ / /_/ / /  / / /_/ / /__/ /_/ / /_/ (__  )
# /_/ /_/\__, /_.___/_/  /_/\__,_/\___/\__,_/ .___/____/
#       /____/                             /_/
#
#            MAPS CAPSLOCK TO CTRL & ESC
#
# TODO: add option to toggle state

setxkbmap -option ctrl:nocaps
xcape -e "Control_L=Escape"
