#!/usr/bin/env bash

#                __
#    _________  / /_  ____
#   / ___/ __ \/ __ \/ __ \
#  (__  ) /_/ / / / / /_/ /
# /____/ .___/_/ /_/ .___/
#     /_/         /_/
#
# requirements: ubuntu, apache
# usage: sudo ./sphp php_version
#
# PPA for old php version: https://launchpad.net/~ondrej/+archive/ubuntu/php

# bash strict mode
set -euo pipefail
IFS=$'\n\t'

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root"
   exit 1
fi

if [ $# != 1 ]; then
    echo "usage: $0 to_version";
    exit 1;
fi

resp=$(php -v)

from_version="php${resp:4:3}"
to_version="php$1"

a2dismod "$from_version"
a2enmod "$to_version"

update-alternatives --set php "/usr/bin/$to_version"
systemctl restart apache2.service
